apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
data:
  MONGO_HOST: mongodb-service
  MONGO_PORT: "27017"
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  # Values are base64 encoded (example: root/password)
  mongo-root-username: cm9vdA==
  mongo-root-password: cGFzc3dvcmQ=
